export { default as Header } from './Header'
export { default as Home } from './Home'
export { default as SinglePage } from './SinglePage'
export { default as SinglePost } from './SinglePost'
export { default as NotFound } from './NotFound'
